@startuml
class FramesBmx {
~ double id
~ int sizeWheel
~ float sizeTubeSup
~ String weightFrame
~ String color
~ String typeBox
~ String material
+ <<Create>> FramesBmx()
+ FramesBmx clonar()
}


class Main {
+ {static} void main(String[])
}

class FrameDesign {
~ int sizeWheel
~ float sizeTubeSup
~ String weightFrame
~ String color
~ String boxType
~ String material
~ Scanner scanner
+ void PrintWelcome()
+ int GetWheelSize()
+ float GetTubeSupSize()
+ String GetWeightFrame()
+ String GetColorFrame()
+ String GetBoxType()
+ String GetFrameMaterial()
}




Cloneable <|.. FramesBmx
@enduml