@startuml
class FramesBmx {
~ int sizeWheel
~ float sizeTubeSup
~ String weightFrame
~ String color
~ String typeBox
~ String material
+ <<Create>> FramesBmx()
+ FramesBmx clonar()
}


class Main {
+ {static} void main(String[])
}

class FrameDesign {
~ int sizeWheel
~ float sizeTubeSup
~ String weightFrame
~ String color
~ String boxType
~ String material
~ int numClones
~ Scanner scanner
+ void PrintWelcome()
+ int GetWheelSize()
+ float GetTubeSupSize()
+ String GetWeightFrame()
+ String GetColorFrame()
+ String GetBoxType()
+ String GetFrameMaterial()
+ int GetNumClones()
}

note left of FrameDesign::PrintWelcome()
Interfaz Welcome
end note
note right of FrameDesign::GetWheelSize()
 1. Set Wheel Size:
end note
note left of FrameDesign::GetTubeSupSize()
 2 . Set Size Superior Tube:
end note
note right of FrameDesign::GetWeightFrame()
 3. Set Weight frame:
end note
note left of FrameDesign::GetColorFrame()
 4. Set Color frame:
end note
note right of FrameDesign::GetBoxType()
 5. Set TypeBox frame:
end note
note left of FrameDesign::GetFrameMaterial()
 6. Set Material Frame:
end note



Cloneable <|.. FramesBmx
@enduml